# Generated by Django 6.0.7 on 2026-07-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ne', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('province', models.CharField(max_length=100)),
                ('centroid_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('centroid_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('rows_upserted', models.IntegerField(default=0)),
                ('rows_rejected', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='districts.district')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPrecip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('precip_mm', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('open_meteo', 'Open-Meteo'), ('dhm', 'DHM')], max_length=32)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_precip', to='districts.district')),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'date'], name='districts_d_distric_f2f0ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('district', 'date', 'source'), name='uniq_district_date_source')],
            },
        ),
        migrations.CreateModel(
            name='SpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_for', models.DateField()),
                ('scale_months', models.PositiveSmallIntegerField(choices=[(3, 'SPI-3'), (6, 'SPI-6'), (12, 'SPI-12')])),
                ('spi_value', models.FloatField(blank=True, null=True)),
                ('severity_class', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_snapshots', to='districts.district')),
            ],
            options={
                'ordering': ['-computed_for', 'scale_months'],
                'constraints': [models.UniqueConstraint(fields=('district', 'computed_for', 'scale_months'), name='uniq_district_thursday_scale')],
            },
        ),
    ]
